version: '3.7'

services:
  mqtt:
    image: secure-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/trigger:/tmp/trigger
      - ./volumes/letsencrypt:/etc/letsencrypt
    logging:
      options:
        max-size: "4m"
        max-file: "10"
    restart: unless-stopped
  certbot:
    image: certbot
    container_name: certbot
    environment:
      - DOMAIN=$DOMAIN
      - EMAIL=$EMAIL
#      - DRYRUN=true
    volumes:
      - ./volumes/letsencrypt:/etc/letsencrypt
      - ./volumes/trigger:/tmp/trigger
    ports:
      - 80:80
      - 443:443
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped


